/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'razing' at '7/26/16 1:03 PM' with Gradle 2.14
 *
 * @author razing, @date 7/26/16 1:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
