/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'razing' at '11/28/16 9:19 AM' with Gradle 2.14
 *
 * @author razing, @date 11/28/16 9:19 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
