apiVersion: v1
kind: Service
metadata:
  name: baldur-tensplit
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-06fbb55190b56b931"
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: baldur
  type: LoadBalancer
  loadBalancerSourceRanges:
  - "10.0.0.0/8"
  - "10.240.0.0/12"
  - "172.16.0.0/12"
