apiVersion: apps/v1
kind: Deployment
metadata:
  name: baldur-deployment
spec:
  selector:
    matchLabels:
      app: baldur
  replicas: 2
  template:
    metadata:
      labels:
        app: baldur
    spec:
        containers:
        - name: baldur
          image: 952478859445.dkr.ecr.us-east-1.amazonaws.com/mkt-devops/mkt-template-docker:latest
