/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'razing' at '8/8/16 1:53 PM' with Gradle 2.14
 *
 * @author razing, @date 8/8/16 1:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
