apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: baldur
  region: us-east-1
  version: "1.15"

vpc:
  subnets:
    private:
      us-east-1b: { id: subnet-00ecb52b }
      us-east-1c: { id: subnet-ea91809d }
    public:
      us-east-1b: { id: subnet-07ecb52c}
      us-east-1c: { id: subnet-ec91809b}

nodeGroups:
  - name: ng-stateless
    labels: { target: stateless }
    minSize: 2
    maxSize: 6
    instancesDistribution: # 25% on demand and 75% spot instances (Spot Fleet)
        maxPrice: 0.015
        instanceTypes: ["t3.small", "t3.medium", "t3a.small", "t3a.medium"]
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 25
        spotInstancePools: 4
    privateNetworking: true
    ssh: # use existing EC2 key
      publicKeyName: ci-k8s
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/baldur: "owned"
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true

managedNodeGroups:
  - name: ng-stateful
    instanceType: t3.medium
    labels: { target: stateful }
    minSize: 2
    maxSize: 5
    volumeSize: 50
    availabilityZones: ["us-east-1b"] # lock this node group to one AZ for shared EBS
    ssh:
      publicKeyName: ci-k8s
    #tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      #k8s.io/cluster-autoscaler/enabled: "true"
      #k8s.io/cluster-autoscaler/baldur: "owned"
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
        ebs: true
        efs: true

fargateProfiles:
  - name: fp-dev
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: dev
        labels: { target: fargate }
  - name: fp-prod
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: prod
        labels: { target: fargate }
  - name: fp-tst
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: tst
        labels: { target: fargate }
  - name: fp-eurc
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: eurc
        labels: { target: fargate }

#cloudWatch:
    #clusterLogging:
        # enable specific types of cluster control plane logs
        #enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
